namespace SourceDepend.CodeGenerators;

internal static class DependencyAttributeCodeGenerator
{
    private const string attributeText = @"// <auto-generated />
[System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
[System.Diagnostics.Conditional(""DependencyGenerator_DEBUG"")]
internal sealed class DependencyAttribute : System.Attribute
{
    internal DependencyAttribute(string alternativePropertyName = null) { }
}
";
    internal static string Generate() => attributeText;
}
